In [3]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [5]:
import numpy as np

In [13]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = [[1,2,3],[4,5,6],[7,8,9]]
print(a[0])
b[0]

[1 2 3]


[1, 2, 3]

In [22]:
a = np.array([1,2,3])

In [25]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [30]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.empty(6)

array([0., 0., 0., 0., 0., 0.])

In [27]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [33]:
cth = np.arange(5,10,2)

In [42]:
#menggabungkan 2 array
np.append(cth, [1,2,3])

#menghapus elemet array di index
np.delete(cth, 0)


#cth = np.append(cth,[1,2,10])
np.sort(cth)


array([ 1,  1,  1,  1,  2,  2,  2,  2,  3,  5,  7,  9, 10, 10, 10])

In [80]:
array_example = np.array([
    [
        [0,1,2,3],
        [4,5,6,7]],

]

)

In [49]:
#untuk melihat dimensi array
print(array_example.ndim)

#untuk melihat total elemet
print(array_example.size)

#untuk melihat elemet
print(array_example.shape)

3
24
(3, 2, 4)


In [56]:
#jumlah total angka di mulai dari nol sampai ke n
a = np.arange(16)
#untuk membuat baris dan kolom
b = a.reshape(16,1)
b

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [63]:
#meningkat dimensi array sebanyak 2 dimensi
display(a)
a2 = a[np.newaxis]

display(a2)
a3 = a2[np.newaxis]
display(a3)

row_vector = a[:,np.newaxis]
row_vector


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]]])

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [69]:
a = np.arange(5)
display(a)
display(a.shape)

b = np.expand_dims(a, axis=0)
display(b)
display(b.shape)

array([0, 1, 2, 3, 4])

(5,)

array([[0, 1, 2, 3, 4]])

(1, 5)

In [71]:
a

array([0, 1, 2, 3, 4])

In [73]:
print(a[2])
print(a[:3])
print(a[::-1])
print(a[-2:])

2
[0 1 2]
[4 3 2 1 0]
[3 4]


In [81]:
array_example

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [85]:
array_example[array_example >= 5]

array([5, 6, 7])

In [87]:
#mengambil element aray sama dengan lima dan lebih
five_up = (array_example >= 5)
array_example[five_up]

array([5, 6, 7])

In [89]:
#mengambil element aray yg habis di bagi
array_example[array_example%2==0]

array([0, 2, 4, 6])

In [91]:
#mengambil element aray menggunakan dan antara yg habis di bagi 2 dan di atas 3
array_example[(array_example%2==0) & (array_example > 3)]

array([4, 6])

In [94]:
a = np.arange(1,11)
#mengambil index ke 3 samapi ke 8
b = a[3:8]
b

array([4, 5, 6, 7, 8])

In [96]:
array_example

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [98]:
a1 = np.array(
    [
        [0,1,],
        [4,5,]
    ]
)

a2 = np.array(
    [
        [2,3,],
        [6,7,]
    ]
)

In [100]:
#menggabungkan atau menumpuk arrry vertikal
np.vstack((a1, a2))

array([[0, 1],
       [4, 5],
       [2, 3],
       [6, 7]])

In [102]:
#menggabungkan atau menumpuk arrry horizontal
np.hstack((a1, a2))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [105]:
display(a)
a2 = a[np.newaxis]
a4 = np.vstack((a2,a2))
a4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [108]:
#spit array
np.hsplit(a4, 5)

[array([[1, 2],
        [1, 2]]),
 array([[3, 4],
        [3, 4]]),
 array([[5, 6],
        [5, 6]]),
 array([[7, 8],
        [7, 8]]),
 array([[ 9, 10],
        [ 9, 10]])]

In [110]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [114]:
b = a.view()
b


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [117]:
#untuk mengcopy array yg kita bikin supaya array asli tidak berubah
c = a.copy()
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [119]:
a = np.arange(3)
b = np.arange(4,7)
print(a)
print(b)
#aritmatika dalam array
print(a + b)
print(a - b)
print(a * b)
print(a / b)

[0 1 2]
[4 5 6]
[4 6 8]
[-4 -4 -4]
[ 0  5 12]
[0.         0.2        0.33333333]


In [124]:
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [125]:
#sum jumlah dari matriks
c.sum()

78

In [127]:
a3

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]]])

In [129]:
#sum jumlah dari matriks
a3.sum()

120

In [131]:
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [134]:
print(c.sum(axis = 0))
print(c.sum(axis = 1))

[15 18 21 24]
[10 26 42]


In [136]:
#perkalian matriks
print(a)
print(a * 1.6)

[0 1 2]
[0.  1.6 3.2]


In [137]:
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [140]:
#mencari nilai minumum array
print(c.min())
#mencari jumlah maksimal array
print(c.max())
#mencari jumlah total array
print(c.sum())
#mencari deviasi standar
print(c.std())


#mencari baris paling rendah
print(c.min(axis=1))
#mencari baris paling tinggi
print(c.max(axis=0))

1
12
78
3.452052529534663
[1 5 9]
[ 9 10 11 12]


In [147]:
#membuat matriks 0
z = np.zeros((6,2))
#membuat matriks 1
o = np.ones((6,2))
#membuat matriks random
r = np.random.random((6,2))

In [162]:
print( z + o)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [164]:
a1 = np.array([[1,2,3],[4,5,6]])
print(a1)

a2 = np.array([[7,8],[9,10],[11,12]])
print(a2)

[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]


In [166]:
np.dot(a1,a2)

array([[ 58,  64],
       [139, 154]])

In [169]:
a1 = np.array([[1,2],[3,4],[5,6]])
print(a1)
print(a1[0])
print(a1[2])
print(a1[0:2])
print(a1[0,1])
print(a1[0][1])

[[1 2]
 [3 4]
 [5 6]]
[1 2]
[5 6]
[[1 2]
 [3 4]]
2
2


In [173]:
display(a1)
print(a1.shape)
print(a1.T)
print(a1.T.shape)

array([[1, 2],
       [3, 4],
       [5, 6]])

(3, 2)
[[1 3 5]
 [2 4 6]]
(2, 3)


In [175]:
a = np.arange(6)

In [177]:
a2 = a[np.newaxis]
a2.T

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [181]:
a2.reshape(-1,3)

array([[0, 1, 2],
       [3, 4, 5]])